name: 'Update flakes'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'

jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update flake inputs
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          nix flake update --commit-lock-file

      - name: Get flake metadata
        id: flake-metadata
        run: |
          # The sed expression strips any control sequences (e.g., the bold text elements)
          body="$(nix flake metadata | sed -E "s/[[:cntrl:]]\[[0-9]{1,3}m//g")"
          # The following encoding is required to have proper multiline strings
          # Also see: https://github.community/t/set-output-truncates-multiline-strings/16852/3
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: flake-updates
          token: ${{ secrets.PAT }}
          title: Update flake inputs
          body: |
            ```
            ${{ steps.flake-metadata.outputs.body }}
            ```

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
